version: '3'

services:
  gotify:
    image: gotify/server:2.4.0
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./gotify/data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_PASS=yourpassword
      - GOTIFY_DEFAULTUSER_NAME=yourusername
      - GOTIFY_SERVER_PORT=80
    networks:
      - brewday-network
  
  brewday:
    image: jpcr3108/brewday:latest
    container_name: brewday
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - BREWDAY_APP_PORT=8080
      - BREWDAY_NOTIFICATION_ENABLED=true
      - BREWDAY_NOTIFICATION_GOTIFY-URL=http://gotify:80
      - BREWDAY_NOTIFICATION_USERNAME=yourusername
      - BREWDAY_NOTIFICATION_PASSWORD=yourpassword
    networks:
      - brewday-network
    depends_on:
      - gotify

networks:
  brewday-network: