FROM golang:1.20-bookworm as builder
ARG VERSION
ENV GO_PROXY=https://proxy.golang.org
WORKDIR /app
COPY . .
RUN apt-get update -y && apt-get install gcc-aarch64-linux-gnu -y
RUN VERSION=${VERSION} BUILD_OUT=./brewday make build-arm

FROM arm64v8/debian:bookworm-slim
COPY --from=builder /app/brewday /brewday
EXPOSE 8080
ENTRYPOINT ["/brewday"]