FROM golang:1.20-bookworm as builder
ARG VERSION
ENV GO_PROXY=https://proxy.golang.org
WORKDIR /app
COPY . .
RUN apt-get update -y && apt-get install gcc-aarch64-linux-gnu -y
RUN VERSION=${VERSION} BUILD_OUT=./brewday make build-arm

FROM arm64v8/alpine:3
COPY --from=builder /app/brewday /brewday
RUN apk add --no-cache libc6-compat gcc musl-dev
COPY --from=builder /app/brewday /brewday
RUN chmod +x /brewday
EXPOSE 8080
ENTRYPOINT ["/brewday"]