CREATE TABLE
    IF NOT EXISTS "recipes" (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        style TEXT,
        batch_size_l REAL,
        initial_sg REAL,
        ibu REAL,
        ebc REAL,
        status INTEGER NOT NULL,
        status_args TEXT,
        mash_malts TEXT,
        mash_main_water REAL,
        mash_nachguss REAL,
        mash_temp REAL,
        mash_out_temp REAL,
        mash_rasts TEXT,
        hop_cooking_time REAL,
        hop_hops TEXT,
        hop_additional TEXT,
        ferm_yeast TEXT,
        ferm_temp TEXT,
        ferm_additional TEXT,
        ferm_carbonation REAL
    );