name: publish-docker
on:
  push:
    tags:
      - "**"

jobs:
  push_docker_hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: jpcr3108/brewday
            platform: linux/amd64
          - dockerfile: ./Dockerfile.arm
            image: jpcr3108/brewday-arm
            platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU (for arm64 builds on x86_64 runners)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          build-args: VERSION=$GITHUB_REF_NAME
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
